namespace:
  name: test

service:
  port: 8111
  type: ClusterIP

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

replicaCount: 3

resources:
  requests:
    cpu: 50m
    memorty: 256Mi

configmap:
  data: "version: alpine"