namespace name: prod
replica count: 2
image repository: nginx
image tag: 1.17.0
resources: CPU 70m and memory 256Mi
service port: 80
configmap data: "version: 1.17.0"

namespace:
  name: prod

service:
  port: 8110
  type: ClusterIP

image:
  repository: nginx
  tag: 1.17.0
  pullPolicy: IfNotPresent

replicaCount: 2

resources:
  requests:
    cpu: 70m
    memory: 256Mi

configmap:
  data: "version: 1.17.0"